### DISCUSSION TITLE
Run ShellCheck on shell scripts inside YAML

### DISCUSSION THREAD

**Discussion by Realiserad** [timonwong/vscode-shellcheck#1347] [Q&A] [answered]
Hello,

I write a lot of Tekton YAML and that means small shell scripts inside YAML.

For example, I dummy like me would write something like:

```yaml
- name: some-tekton-step
  image: gg.io/masterblaster
  script: |
    #!/bin/sh
    source foo.sh # Oops, SC3046
    if [[ -f ".jx/setup.sh" ]]; then # whoha, SC3010
       echo "Doing shell magic"
    fi
```

What I typically do now, is to copy paste the shell part into a new document to ensure there are no warnings, is there a better way?
